# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AsyncMessagingClient < Formula
  desc "Sends and receives messages in an asynchronous way to or from different Cloud messaging services."
  homepage "https://fhopfensperger.github.io"
  version "0.2.9"
  license "Apache 2.0"

  depends_on "go" => :optional
  depends_on "git" => :optional

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/fhopfensperger/async-messaging-client/releases/download/v0.2.9/async-messaging-client_darwin_arm64.tar.gz"
      sha256 "9fbb655faaf67b2c3637ed9cdf5d5f38c1077bb720db0d3b61e75beadffb2596"

      def install
        bin.install "async-messaging-client"
        bash_completion.install "completions/async-messaging-client.bash" => "async-messaging-client"
        zsh_completion.install "completions/async-messaging-client.zsh" => "_async-messaging-client"
        fish_completion.install "completions/async-messaging-client.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/fhopfensperger/async-messaging-client/releases/download/v0.2.9/async-messaging-client_darwin_amd64.tar.gz"
      sha256 "93be70717baa3825aa90238bde35be9be89892790a2eb53d7832dbeac8dac927"

      def install
        bin.install "async-messaging-client"
        bash_completion.install "completions/async-messaging-client.bash" => "async-messaging-client"
        zsh_completion.install "completions/async-messaging-client.zsh" => "_async-messaging-client"
        fish_completion.install "completions/async-messaging-client.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/fhopfensperger/async-messaging-client/releases/download/v0.2.9/async-messaging-client_linux_amd64.tar.gz"
      sha256 "d57c29cd18b520b5e3ddb358646b2ed18511974cdf55125503146ad2d4b3060f"

      def install
        bin.install "async-messaging-client"
        bash_completion.install "completions/async-messaging-client.bash" => "async-messaging-client"
        zsh_completion.install "completions/async-messaging-client.zsh" => "_async-messaging-client"
        fish_completion.install "completions/async-messaging-client.fish"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/fhopfensperger/async-messaging-client/releases/download/v0.2.9/async-messaging-client_linux_armv6.tar.gz"
      sha256 "3721aa5c9c4ca640e9375b4777b3a030cf4ce85e77327d5160c005baeee14f70"

      def install
        bin.install "async-messaging-client"
        bash_completion.install "completions/async-messaging-client.bash" => "async-messaging-client"
        zsh_completion.install "completions/async-messaging-client.zsh" => "_async-messaging-client"
        fish_completion.install "completions/async-messaging-client.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fhopfensperger/async-messaging-client/releases/download/v0.2.9/async-messaging-client_linux_arm64.tar.gz"
      sha256 "205895ba0ccf8996711912a57f2eaf511edb05fed6253a5484a2532382be2713"

      def install
        bin.install "async-messaging-client"
        bash_completion.install "completions/async-messaging-client.bash" => "async-messaging-client"
        zsh_completion.install "completions/async-messaging-client.zsh" => "_async-messaging-client"
        fish_completion.install "completions/async-messaging-client.fish"
      end
    end
  end

  test do
    system "#{bin}/async-messaging-client -v"
  end
end
