# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitReleaser < Formula
  desc "Command line tool to create release branches and tags"
  homepage "https://fhopfensperger.github.io"
  version "0.3.11"
  license "Apache 2.0"

  depends_on "git" => :optional
  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fhopfensperger/git-releaser/releases/download/v0.3.11/git-releaser_darwin_amd64.tar.gz"
      sha256 "9abcac9822e041eb72a64b68a202fb58f67011fa804c2a06f56e66bbca7aa23e"

      def install
        bin.install "git-releaser"
        bash_completion.install "completions/git-releaser.bash" => "git-releaser"
        zsh_completion.install "completions/git-releaser.zsh" => "_git-releaser"
        fish_completion.install "completions/git-releaser.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fhopfensperger/git-releaser/releases/download/v0.3.11/git-releaser_darwin_arm64.tar.gz"
      sha256 "470a8ed3fc4eb1044db4d1e056499ce2916828aa3c345dd94f16758df9b4bce1"

      def install
        bin.install "git-releaser"
        bash_completion.install "completions/git-releaser.bash" => "git-releaser"
        zsh_completion.install "completions/git-releaser.zsh" => "_git-releaser"
        fish_completion.install "completions/git-releaser.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/fhopfensperger/git-releaser/releases/download/v0.3.11/git-releaser_linux_armv6.tar.gz"
      sha256 "4a7469056aefcce07f8a21c4ee3ebefa4ad5ba2bbb78bbd97beb738b70593ea2"

      def install
        bin.install "git-releaser"
        bash_completion.install "completions/git-releaser.bash" => "git-releaser"
        zsh_completion.install "completions/git-releaser.zsh" => "_git-releaser"
        fish_completion.install "completions/git-releaser.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fhopfensperger/git-releaser/releases/download/v0.3.11/git-releaser_linux_arm64.tar.gz"
      sha256 "de9f15f7b66f8647567ad9a22eda72d4cdbd527d6803dbdeebd48e44da171071"

      def install
        bin.install "git-releaser"
        bash_completion.install "completions/git-releaser.bash" => "git-releaser"
        zsh_completion.install "completions/git-releaser.zsh" => "_git-releaser"
        fish_completion.install "completions/git-releaser.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/fhopfensperger/git-releaser/releases/download/v0.3.11/git-releaser_linux_amd64.tar.gz"
      sha256 "c8f593b077aa604c88aff0e1646b0e07ee4e210d6c05974a4ce6f5068d1684d9"

      def install
        bin.install "git-releaser"
        bash_completion.install "completions/git-releaser.bash" => "git-releaser"
        zsh_completion.install "completions/git-releaser.zsh" => "_git-releaser"
        fish_completion.install "completions/git-releaser.fish"
      end
    end
  end

  test do
    system "#{bin}/git-releaser -v"
  end
end
