# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitReleaser < Formula
  desc "Command line tool to create release branches and tags"
  homepage "https://fhopfensperger.github.io"
  version "0.3.10"
  license "Apache 2.0"

  depends_on "go" => :optional
  depends_on "git" => :optional

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/fhopfensperger/git-releaser/releases/download/v0.3.10/git-releaser_darwin_arm64.tar.gz"
      sha256 "fb68d69436c9b29cb6e9ac5db01a5dd6854febf0da884fc19601b65143b190af"

      def install
        bin.install "git-releaser"
        bash_completion.install "completions/git-releaser.bash" => "git-releaser"
        zsh_completion.install "completions/git-releaser.zsh" => "_git-releaser"
        fish_completion.install "completions/git-releaser.fish"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/fhopfensperger/git-releaser/releases/download/v0.3.10/git-releaser_darwin_amd64.tar.gz"
      sha256 "2f6f4c8ca04c3f9c13a6ebddde4cc2991d95fc0bab7267ffc9730ca8590f60ca"

      def install
        bin.install "git-releaser"
        bash_completion.install "completions/git-releaser.bash" => "git-releaser"
        zsh_completion.install "completions/git-releaser.zsh" => "_git-releaser"
        fish_completion.install "completions/git-releaser.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/fhopfensperger/git-releaser/releases/download/v0.3.10/git-releaser_linux_amd64.tar.gz"
      sha256 "0ac26f555c3455e191498710b95f3e64e7f664d54f9ccef5ddf757c2e6c2b00b"

      def install
        bin.install "git-releaser"
        bash_completion.install "completions/git-releaser.bash" => "git-releaser"
        zsh_completion.install "completions/git-releaser.zsh" => "_git-releaser"
        fish_completion.install "completions/git-releaser.fish"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/fhopfensperger/git-releaser/releases/download/v0.3.10/git-releaser_linux_armv6.tar.gz"
      sha256 "b99e8634fa1665c7904ade7340789aa31242be822434b58d98cb6ca84acb9ee5"

      def install
        bin.install "git-releaser"
        bash_completion.install "completions/git-releaser.bash" => "git-releaser"
        zsh_completion.install "completions/git-releaser.zsh" => "_git-releaser"
        fish_completion.install "completions/git-releaser.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fhopfensperger/git-releaser/releases/download/v0.3.10/git-releaser_linux_arm64.tar.gz"
      sha256 "f4e0e260485f69462400de3ba922c61365f4cec796d96b6f0a97e7ac7b2f030f"

      def install
        bin.install "git-releaser"
        bash_completion.install "completions/git-releaser.bash" => "git-releaser"
        zsh_completion.install "completions/git-releaser.zsh" => "_git-releaser"
        fish_completion.install "completions/git-releaser.fish"
      end
    end
  end

  test do
    system "#{bin}/git-releaser -v"
  end
end
