# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JsonLogToHumanReadable < Formula
  desc "Transforms json log into human readable output"
  homepage "https://fhopfensperger.github.io"
  version "0.2.5"
  license "Apache 2.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fhopfensperger/json-log-to-human-readable/releases/download/v0.2.5/json-log-to-human-readable_0.2.5_darwin_amd64.tar.gz"
      sha256 "a10f17893d7796563fdb9c65e3bb133e265dd0b16054e58d342b819aeac00924"
    end
    if Hardware::CPU.arm?
      url "https://github.com/fhopfensperger/json-log-to-human-readable/releases/download/v0.2.5/json-log-to-human-readable_0.2.5_darwin_arm64.tar.gz"
      sha256 "752ecfced27cda5baf6862bcebc4519aab27b8bc57cf3cee433293c1c3266666"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/fhopfensperger/json-log-to-human-readable/releases/download/v0.2.5/json-log-to-human-readable_0.2.5_linux_amd64.tar.gz"
      sha256 "1e05c277fc06361a357a39d4d8670d272be2baca18f868e37d4805a8ac6efd05"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/fhopfensperger/json-log-to-human-readable/releases/download/v0.2.5/json-log-to-human-readable_0.2.5_linux_armv6.tar.gz"
      sha256 "747df9e3d649cc53f17cdf2036716e5845902c14f0982ea3b0814c0fed0c0738"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/fhopfensperger/json-log-to-human-readable/releases/download/v0.2.5/json-log-to-human-readable_0.2.5_linux_arm64.tar.gz"
      sha256 "ce697b0ce2711c212c9b08538c01af08dd3269c858482cfdd5833073857ba0d7"
    end
  end

  depends_on "go" => :optional
  depends_on "git" => :optional

  def install
    bin.install "json-log-to-human-readable"
  end

  test do
    system "#{bin}/json-log-to-human-readable -v"
  end
end
