# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JsonLogToHumanReadable < Formula
  desc "Transforms json log into human readable output"
  homepage "https://fhopfensperger.github.io"
  version "0.2.14"
  license "Apache 2.0"

  depends_on "git" => :optional
  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fhopfensperger/json-log-to-human-readable/releases/download/v0.2.14/json-log-to-human-readable_0.2.14_darwin_amd64.tar.gz"
      sha256 "eaa6da195967f937f0fabbea0d5c6cc6904dd8223d1b9f044d09421a52171f0b"

      def install
        bin.install "json-log-to-human-readable"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fhopfensperger/json-log-to-human-readable/releases/download/v0.2.14/json-log-to-human-readable_0.2.14_darwin_arm64.tar.gz"
      sha256 "0ddeb3b3440784464c9d9dbda15afd0e4b79be3c358b2e17d6470bc81bb7a73d"

      def install
        bin.install "json-log-to-human-readable"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/fhopfensperger/json-log-to-human-readable/releases/download/v0.2.14/json-log-to-human-readable_0.2.14_linux_amd64.tar.gz"
        sha256 "a5c4f1c81267cdc6a283198935e393aad7e1686d5e432806391989bcc37c26bb"

        def install
          bin.install "json-log-to-human-readable"
        end
      end
    end
    if Hardware::CPU.arm?
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/fhopfensperger/json-log-to-human-readable/releases/download/v0.2.14/json-log-to-human-readable_0.2.14_linux_armv6.tar.gz"
        sha256 "c772e777ceeb6c29e36dc76977622a0c2ba7ec76dd4594c8dac4fb02b6a5ea54"

        def install
          bin.install "json-log-to-human-readable"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/fhopfensperger/json-log-to-human-readable/releases/download/v0.2.14/json-log-to-human-readable_0.2.14_linux_arm64.tar.gz"
        sha256 "3e58bb83d072377de0e0f93ed6ae3d037c8e23c74e50364cec89f39b8f086ba4"

        def install
          bin.install "json-log-to-human-readable"
        end
      end
    end
  end

  test do
    system "#{bin}/json-log-to-human-readable -v"
  end
end
